# .github/workflows/ci.yml
name: Node CI (pnpm)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 1 ⟶ check out the code
      - uses: actions/checkout@v4

      # 2 ⟶ install the pnpm CLI once per job (fast: ~200 ms)
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10          # any exact/semver range works

      # 3 ⟶ set up Node and enable built‑in pnpm cache
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm          # hashes pnpm‑lock.yaml for you

      # 4 ⟶ install dependencies reproducibly
      - name: Install deps
        run: pnpm install --frozen-lockfile

      # 5 ⟶ quality gates
      - name: Lint (eslint)
        run: pnpm run lint --if-present
      - name: Unit tests
        run: pnpm test --if-present

      # 6 ⟶ build your Vite app
      - name: Build (Vite)
        run: CI=true pnpm run build

      # 7 ⟶ store build output once (from Node 20)
      - name: Upload dist artifact
        if: matrix.node-version == '20.x'
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  # ---------- OPTIONAL: auto‑deploy to GitHub Pages ----------
  deploy:
    needs: test-build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist

      - name: Configure Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: vite

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
